# Generated by Django 2.0.1 on 2020-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
