# Generated by Django 2.0.1 on 2020-02-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_auto_20200224_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_url',
            new_name='Url',
        ),
    ]
