# Generated by Django 2.0.1 on 2020-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_auto_20200224_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=255)),
                ('ori_url', models.TextField()),
            ],
        ),
    ]
